services:
  db:
    image: postgres:latest
    container_name: metagallery-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1234:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
