name: Deploy Action
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt install openssh-client
      - name: connect
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_CONFIG }}" >.ssh/config
          echo "${{ secrets.SSH_PRIVKEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBKEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
      - name: test file creation
        run: |
          ssh ame-droplet
          echo hola>hola
