name: Deploy Action
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: system deps
        run: |
          sudo apt install --upgrade -y openssh-client openssh-known-hosts openssh-server
      - name: ssh setup
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh/
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVKEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBKEY }}" | tr -d '\r' > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          ssh-add -vvv
          ls ~/.ssh/
          ssh-keyscan -H "${{ secrets.SSH_IP }}" >> ~/.ssh/known_hosts
          ssh -vT "bauer@${{ secrets.SSH_IP }}" "echo hola>hola"

