name: Deploy Action
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: system deps
        run: |
          sudo apt install --upgrade -y openssh-client openssh-known-hosts openssh-server
      - name: ssh setup
        run: |
          mkdir -p ~/.ssh/
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVKEY }}" | tr -d '\r' | ssh-add -vvv -
          echo "added private key"
          ssh-keyscan -H "${{ secrets.SSH_IP }}" >> ~/.ssh/known_hosts
      - name: test file creation
        run: |
          ssh -vT "bauer@${{ secrets.SSH_IP }}" "echo hola>hola"

