name: Deploy Action
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt install openssh-client
      - name: connect
        env:
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        run: |
          mkdir -p ~/.ssh/
          echo $SSH_CONFIG
