name: Deploy Action
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: system deps
        run: |
          exit 0
          sudo apt install --upgrade -y openssh-client openssh-known-hosts openssh-server
      - name: ssh setup
        run: |
          exit 0
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh/
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVKEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBKEY }}" | tr -d '\r' > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-add -vvv
          ls ~/.ssh/
          ssh-keyscan -H "${{ secrets.SSH_IP }}" >> ~/.ssh/known_hosts
      - name: deploy
        run: |
          exit 0
          ssh -vT "bauer@${{ secrets.SSH_IP }}" "cd ~/clones/metagallery/stiller-backend && git pull"
